name: Action test on MacOS

on:
  schedule:
    - cron: "0 4 * * MON-FRI" # Runs at 04:00 UTC
  push:
  workflow_dispatch:

jobs:
  macos-minimal:
    runs-on: macos-latest
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v3
      - id: tag
        uses: GuillaumeFalourd/get-release-or-tag@main
      - name: tag
        run: echo "TAG ${{ steps.tag.outputs.tag }}"
