on: [push, release]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Action
        uses: ./ # Uses an action in the root directory
        id: tag
        # with:
        #   who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the tag
        run: echo "The tag was ${{ steps.tag.outputs.tag }}"