name: Release

on:
  release:
    types:
      - published

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - id: tag
        uses: GuillaumeFalourd/get-release-or-tag@main
      - name: tag
        run: echo "TAG ${{ steps.tag.outputs.tag }}"
